# Práctica II - Visualización de datos M2.859

dataset = https://analisi.transparenciacatalunya.cat/Turisme/Establiments-d-allotjament-tur-stic-inscrits-al-Re/t2h3-cgys/about_data

---

In [2]:
import pandas as pd
import matplotlib as plt

In [3]:
# cargar datos
file_path = "/content/Establiments_d_allotjament_tur_stic_inscrits_al_Registre_de_Turisme_de_Catalunya_20250609.csv"
df = pd.read_csv(file_path)
df

<ipython-input-3-1645990342>:3: DtypeWarning: Columns (20,21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

,Tipus establiment,Número inscripció,Dígit de control,Rètol,Estat,Tipus de via,Nom de la via,Número,Pis,Porta,...,Unitat d'allotjament,Total places,Total estances,SSTT,Marca turística,CIF,Raó Social del titular,Nom del titular,Primer cognom,Segon cognom
0,Apartaments Turístics,ATB-000002,59,Voramar,Alta,Carrer,Barques,2,NaN,NaN,...,Apartaments,36.0,18.0,Barcelona,Costa Barcelona,B63470942,"CASTELLISCON, SL",No aplica,No aplica,No aplica
1,Apartaments Turístics,ATB-000003,66,Gutenberg,Alta,Passatge,Gutenberg,7,NaN,NaN,...,Apartaments,170.0,85.0,Barcelona,Barcelona,A08433989,"APARTAMENTOS GUTENBERG, SA",No aplica,No aplica,No aplica
2,Apartaments Turístics,ATB-000004,61,Montserrat,Alta,Carrer,Antoni Gaudí,11,NaN,NaN,...,Apartaments,12.0,6.0,Barcelona,Costa Barcelona,No aplica,No aplica,Montserrat,Bartes,Abella
3,Apartaments Turístics,ATB-000005,3,Silver,Alta,Carrer,Breton de los Herreros,26,NaN,NaN,...,Apartaments,98.0,49.0,Barcelona,Barcelona,A08139859,"PROYECTOS E INMUEBLES, S. A",No aplica,No aplica,No aplica
4,Apartaments Turístics,ATB-000006,63,Castellmar,Alta,Passeig,Marítim,156,NaN,NaN,...,Apartaments,22.0,10.0,Barcelona,Costa Barcelona,B61933511,"MARFINA APARTAMENTOS, SL",No aplica,No aplica,No aplica
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112555,Turisme rural,PVA-000639,83,Bòrda Gilhamuc,Alta,Carrer,Era Carrèra,10,NaN,NaN,...,Habitació,6.0,3.0,Val d'Aran,Val d'Aran,No aplica,No aplica,Mireia,Boya,Busquet
112556,Turisme rural,PVA-000640,72,Pico Rusell,Alta,Carrer,Laca,12,NaN,NaN,...,Habitació,10.0,4.0,Val d'Aran,Val d'Aran,No aplica,No aplica,Juan Luís,De,Pablo Pérez
112557,Turisme rural,PVA-000641,75,CASA CHIN,Alta,Carrer,Major,32,NaN,NaN,...,Habitació,12.0,5.0,Val d'Aran,Val d'Aran,No aplica,No aplica,JORDI,ARJÓ,FRANCÉS
112558,Turisme rural,PVA-001015,93,TORISME RURAU CASA REY,Alta,Carrer,SASPLAS,6,NaN,NaN,...,Habitació,12.0,5.0,Val d'Aran,Val d'Aran,No aplica,No aplica,Carmen,Castellarnau,Lafont
112559,Turisme rural,PVA-001379,85,ES DE PAU AGROTURISME,Alta,Carrer,Sant Esteve,9,NaN,NaN,...,Habitació,5.0,3.0,Val d'Aran,Val d'Aran,No aplica,No aplica,Jose Maria,Moga,Cortinat

In [4]:
# Exploración inicial - tipo de datos
print("Tipos de datos por columna")
print(df.dtypes)

Tipos de datos por columna
Tipus establiment           object
Número inscripció           object
Dígit de control             int64
Rètol                       object
Estat                       object
Tipus de via                object
Nom de la via               object
Número                      object
Pis                         object
Porta                       object
Escala                      object
Bloc                        object
Codi Postal                  int64
Municipi                    object
Codi Municipi (IDESCAT)      int64
Comarca                     object
Codi Comarca (IDESCAT)       int64
Província                   object
Referència cadastral        object
Cèdula d'habitabilitat      object
Grup                        object
Modalitat                   object
Categoria                   object
Unitat d'allotjament        object
Total places               float64
Total estances             float64
SSTT                        object
Marca turística             object
CIF                         object
Raó Social del titular      object
Nom del titular             object
Primer cognom               object
Segon cognom                object
dtype: object

In [5]:
# resumen estadístico
print("\nResumen estadístico del DataFrame:")
print(df.describe(include='all'))

Resumen estadístico del DataFrame:
               Tipus establiment Número inscripció  Dígit de control  \
count                     112560            112560     112560.000000
unique                         5            112560               NaN
top     Habitatges d'ús turístic        PVA-000010               NaN
freq                      106002                 1               NaN
mean                         NaN               NaN         48.106725
std                          NaN               NaN         27.986260
min                          NaN               NaN          0.000000
25%                          NaN               NaN         24.000000
50%                          NaN               NaN         48.000000
75%                          NaN               NaN         72.000000
max                          NaN               NaN         99.000000

                    Rètol   Estat Tipus de via Nom de la via  Número    Pis  \
count              112559  112560       112560        112560  112560  71017
unique              13181       1           39         25304    3186    735
top     Sense especificar    Alta       Carrer         Major       1      1
freq                97128  112560        75983          1018    5214  18529
mean                  NaN     NaN          NaN           NaN     NaN    NaN
std                   NaN     NaN          NaN           NaN     NaN    NaN
min                   NaN     NaN          NaN           NaN     NaN    NaN
25%                   NaN     NaN          NaN           NaN     NaN    NaN
50%                   NaN     NaN          NaN           NaN     NaN    NaN
75%                   NaN     NaN          NaN           NaN     NaN    NaN
max                   NaN     NaN          NaN           NaN     NaN    NaN

        Porta  ... Unitat d'allotjament  Total places  Total estances    SSTT  \
count   72366  ...               112556  30930.000000    10027.000000  112560
unique   1129  ...                    3           NaN             NaN       8
top         1  ...            Habitació           NaN             NaN  Girona
freq    16315  ...               111890           NaN             NaN   47914
mean      NaN  ...                  NaN     25.080278       28.022639     NaN
std       NaN  ...                  NaN    131.777804       83.149035     NaN
min       NaN  ...                  NaN      1.000000        1.000000     NaN
25%       NaN  ...                  NaN      4.000000        3.000000     NaN
50%       NaN  ...                  NaN      6.000000        4.000000     NaN
75%       NaN  ...                  NaN     10.000000       13.000000     NaN
max       NaN  ...                  NaN   5259.000000     1753.000000     NaN

        Marca turística        CIF  Raó Social del titular Nom del titular  \
count            112560     112559                  112553          112560
unique               11       9774                    9784             977
top         Costa Brava  No aplica               No aplica       No aplica
freq              45227      85705                   85697          109533
mean                NaN        NaN                     NaN             NaN
std                 NaN        NaN                     NaN             NaN
min                 NaN        NaN                     NaN             NaN
25%                 NaN        NaN                     NaN             NaN
50%                 NaN        NaN                     NaN             NaN
75%                 NaN        NaN                     NaN             NaN
max                 NaN        NaN                     NaN             NaN

       Primer cognom Segon cognom
count         112560       112560
unique          1696         1636
top        No aplica    No aplica
freq          109533       109708
mean             NaN          NaN
std              NaN          NaN
min              NaN          NaN
25%              NaN          NaN
50%              NaN          NaN
75%              NaN          NaN
max              NaN          NaN

[11 rows x 33 columns]

In [6]:
# ver valores categóricos únicos
for col in df.select_dtypes(include='object').columns:
    print(f"Unique values in column '{col}':")
    print(df[col].unique())
    print()

Unique values in column 'Tipus establiment':
['Apartaments Turístics' 'Càmpings' 'Hotels' "Habitatges d'ús turístic"
 'Turisme rural']

Unique values in column 'Número inscripció':
['ATB-000002' 'ATB-000003' 'ATB-000004' ... 'PVA-000641' 'PVA-001015'
 'PVA-001379']

Unique values in column 'Rètol':
['Voramar' 'Gutenberg' 'Montserrat' ... 'CASA CHIN'
 'TORISME RURAU CASA REY' 'ES DE PAU AGROTURISME']

Unique values in column 'Estat':
['Alta']

Unique values in column 'Tipus de via':
['Carrer' 'Passatge' 'Passeig' 'Via' 'Carretera' 'Avinguda' 'Baixada'
 'Rambla' 'Disseminat' 'Plaça' 'Cases' 'Edifici' 'Barri' 'Camí'
 'Urbanització' 'Travessia' 'Lloc' 'Poblat' 'Partida' 'Polígon' 'Sector'
 'Prolongació' 'Torrent' 'Travessera' 'Ronda' 'Gran Via' 'Grup' 'Pujada'
 'Parc' 'Placeta' 'Carreró' 'Colònia' 'Xalet' 'Apartament' 'Veïnat' 'Bloc'
 'Glorieta' 'Barranc' '-']

Unique values in column 'Nom de la via':
['Barques' 'Gutenberg' 'Antoni Gaudí' ... 'Mètge Campà' 'Era Carrèra'
 'SASPLAS']

Unique values in column 'Número':
['2' '7' '11' ... 'KM 8,4' 'KM 17,5' 'POL. 44']

Unique values in column 'Pis':
[nan 'Baix' '1' '2' '3' 'PL 1A' 'BAIXOS' '4' 'pral' '5' 'Entresol' 'PPAL'
 '2º' 'ENTLO12' 'EN' 'PRAL' 'Principal' '1 i 2' 'PRINCIPAL' 'enl' 'Casa'
 'PR' 'Bxs' 'en' 'B' '7' 'PPRAL' 'CASA' 'Local' '3-4' 'bx' 'BJ' 'At'
 'Àtic' 'Pr' '6' '12' '8' '25' '9' '17' '21' '22' '23' '10' '14' 'AT'
 'sat' 'SA' 'entresol' 'Ent' 'Entr.' 'Pral' 'ÀTIC' 'SO' '03' 'ENTRESUELO'
 '13' '02' '04' '05' 'ATIC' '15' '16' 'ENTRESOL' 'atico' '20' 'EST' 'SbAt'
 'Baixos' '01' 'Entresuelo' 'bajos' 'ATICO' 'ENT' 'ENTL' 'atic'
 'Sobreàtic' 'principal' '11' 'àtic' '08' 'baixos' 'Atic' 'baix' 'Prpl'
 'apart' '18' 'Entressòl' 'entlo.' 'BA' '06' 'BJS' 'bxs' 'gran' '1r'
 'Entr' 'entresuelo' 'sàt' 'ap' 'A' '1 D' 'ssot' 'ent.' 'Bajos'
 'sobreàtic' '135' 'BAJOS' 'PRAL.' '5è' '4t' 'Entresòl' 'ent' '2-2' '3è'
 'entre' 'SOBREATIC' 'BAJO' 'Bj' 't' 'sot 2' '19' '24' '13-12' 'Baix 1'
 'Atico 1' '1er' '406' 'ÁTICO' 'bjs' 'Primero' 'sot' 'Segon' 'Tercer'
 'Quart' 'Pri' 'OD' 'SS' 'âtic' 'F' '40' 'Baix INT' 'int' '7, 115a' 'sòt'
 '2n' '1R' 'Sot' 'BI' 'pal' 'ENL' '00' 'P 16' 'Espanya' 'casa' 'BXS'
 'sàtic' '2-3a' 'at' 'ba' 'C' '6é' '5é' '30-12' '410' '14é' 'Ap' 'AP'
 '38-A' 'E-6' '51' '61' 'Dreta' 'Esquerra' '123' '1e' '121' '2B' 'servei'
 'convidats' 'plbxa' 'C2' 'B5' 'Bis' '168' 'OM' '129' 'Semisoterra' 'Apt'
 'SAT' 'S1' 'àtc' 'Pal' 'Pl' 'Àtc' 'x' '1-1' 'CASA 3' 'semisòtano' 'par54'
 '12 Bis' 'ATC' 'UN' 'Soterrani' 'PB' 'SOTANO' '6(PLANTA5)' 'Baix Esquer'
 'Casa 10' 'BX' 'BAIX' 'PRIMER' 'PBJ' 'Atico' 'Bx' 'Bjos' 'Primer' 'BIS'
 'SOBRE ATIC' 'bxos' 'sobre atic' '1-7' 'SOBREATICO' 'so' 'B-2' 'P B'
 '4art-1a' 'S-1' 'PBX' '1r-2n' '3r-4rt' '-2' 'b' '3r' '2ON' 'BAIXA' 'SM'
 'Baix K' 'PJ' '307' '308' 'BXOS' '306' '316' '318' '317' '802' '907'
 '1216' '1217' 'D' 'P01' 'Pltabaixa' 'pltabaixa' 'Àtic 1' '2D' 'E' 'E13'
 'C4' '54' 'A-1' 'B-1' '1 J26' 'F-12' 'B-6' 'A-3' '218' '313' '26' '27'
 '28' '108' '109' '309' 'Baix 4' 'D-7' 'âtic 1a' 'Entresol J' '102' 'A1'
 '1sud' '1B' '322' 'F10' 'G1' 'M38C' 'M36A' 'R4B' 'M25C' 'M27A' 'M21A'
 'M20A' 'M15B' 'M49A' 'M37A' 'M3B' 'M13C' 'M10B' 'M20C' 'M4B' 'R15B'
 'GP38' 'B47' 'R38A' 'M12A' 'M29C' 'M17A' 'B19' 'R20B' 'B16' 'R44B' 'B9'
 'M47C' 'M45C' 'R25A' 'M31C' '31' 'M29A' 'B26' 'âtic 2' 'B1' '15-17'
 '16-18' 'D-23' '4r' '20103' '3D' '2C' '29' '30' '32' '33' '34' '35' '115'
 '116' '122' '36' '42' '43' '203' '204' 'N3' 'M9' '223' '603' '33A' 'F1'
 'BXS.' '4B' '7B' 'En' '311' '1-5' 'bj' '1-F' 'M5B' 'M6B' 'M7B' 'M19B'
 'M22B' 'M8C' 'M9C' 'M44C' 'B14' 'B22' 'B30' 'B50' 'M2C' '0' 'Bxos' 'D4'
 'E5' '105' '64' '1505' 'B 2' 'A2' 'A3' 'B2' 'B3' '301' 'C1' '74' '302'
 'porta 3' 'C3' 'D1' 'D2' 'D3' 'SN' 'CA-103' 'Jardi' '47' 'E2' 'A15' 'E3'
 'EH-3' '17-10' 'B-13' 'F-3' '3B' '.' 'B4' 'G' 'A4' '303' '83' 'G 7' 'B6'
 'F1-F15' '37' 'entlo' 'Baix 5' 'Baix A' 'Baix B' 'l' 'Illa P1' 'AP 4'
 'SM5' 'D-1' '903' 'C-4' 'D-2' 'E-2' 'Baix C' 'D5' 'ppal' '46' '313A'
 '150' '151' '158' '159' '160' '2-A' '57' 'E 1' 'H 2' 'H 4' 'C 2' 'H' '-1'
 'bustia' 'P1 00' 'BXS1' 'P' 'PP' 'Par' '1 F' '125' '130' 'bc' 'ENTR'
 '906' '113' '103' '104' '106' '107' '110' '111' '112' '114' '117' '118'
 '152' '153' '154' '155' '156' '157' '162' '163' '164' '165' '166' 'dta'
 's' 'AM' 'BAIX2' '68' 'atc' '2 C' 'B0' '09' 'SSOT' 'Baix 12' '404'
 'parcela146' '101A' 'Àtic C' 'U' '66' '3q' 'ÂTIC' 'casa 8' 'casa 18'
 'PltaBaixa' 'baix-1' 'D17' 'Ba' 'Ap 7' 'S' 'Semisot' 'casa 4' '4art'
 'Bis B' 'NR F1' 'Casa A' 'Casa B' 'Casa C' '305' 'CA' 'Bis A' '4 (ÀTIC)'
 '401' 'S-5' 'Duplex' 'S5' 'A0' 'Àtic 2' '403' 'H1' 'Baix 2' 'Casa 2'
 '2-1' '206' '219' '1-2' '202' 'casa 9' '101a' 'E 204' 'APART2' 'sc'
 'primero' '07' '611' 'Baix 1A' '101' 'Casa 8' '1è' 'APT 33' '3ro' '2I'
 'Sote' 'e' '205' 'P/B' '321' 'Baig' 'A6' '4 (ATIC)' 'Baix 203' '127'
 'PLANTA BAI' '1 BX' 'SEMISOT' '4-5' 'Pl.baixa' '-' 'Baixo' 'bajo'
 'Baixos 1' 'SECT. E5' 'J' 'K' 'SC' '1 Esquerra' 'A01' '2 PIS' 'H2' '3r6'
 'PLO' 'BC' '1 I 2' 'Segunda' '1º' '2N' 'Baixos 4' '2 Baix' '120' '220'
 '221' '222' '320' '5 pt607' '607' '3 pt404' '4 pt508' '2pt306' '5 pt609'
 '1 pt207' 'BXpt108' '4 pt501' '5 pt601' '4 pt 501' '1pt201' '512' '2 1A'
 'Casa 5' '201' '207' '208' '209' '402' '302è' '7 Àtic' '2 pt305' 'Pis 1'
 'Bxs.' '4 B' 'SMT' 'J-519' 'I-517' 'K-424' 'A-401' 'E1' 'bxs2' '72'
 '3 pt408' 'Baix PT101' '5 pt603' 'B10' 'B74' 'Pis 6' 'AS' 'parc 1'
 'Pis 5' 'G2 C3' 'I-1' 'Baix PT104' 'parc 31' 'Bajo' '45' '942' 'BXA' '6D'
 'Parc74' 'Pol1' 'BE' 'ÀTC' 'Px' 'Q' '48' 'SÀ' 'parc 58' 'etr' 'CASA B'
 'Pis 2' 'pis 2' 'Pis2' 'Pis 4' 'Pis 3' 'PIs 7' 'Pis 8' 'Pis 7' 'PIS Baix'
 'PIS 3' 'Baix 2A' '49' 'CASA H2' 'BX-A' '56' 'Ppal' '414' '58'
 'Entre piso' 'BAI' 'P Baix' 'Local Baix' '1-1A' '675' '323' 'PL Baix'
 '315' 'Baix IZQUI' '3o' '304' '271' 'porta' '1 izquerda' '536' 'CASA 14'
 'bxa' '+1' '3º' '4º' '1 Àt' 'bxsA' '412' 'BX A' '1G' '553' 'H-3' 'casaA'
 '4H' 'bx11' 'parcella' 'BAX' 'ZII' 'E-1' '1N' 'entsl' 'Entsol' '3Àt'
 'CASA 13' '1-3' 'Entresol 1' 'Entre' 'segon' 'PBAIXA' 'PBA' 'entl' 'P1'
 'Segundo' 'entr' 'N' 'ï¿¿tic' '3E' 'BO' 'Bo' 'sm' 'as' 'sa' '3 - A' 'bo'
 '4º00' 'P02' 'b0' 'PL00' 'E-5' '1ER' 'PARC23' 'Par18k10']

Unique values in column 'Porta':
[nan 'C' '3' ... 'C0' '1r' 'Dr']

Unique values in column 'Escala':
[nan 'A' '1' 'P81' 'B' 'Principal' 'b' '2' 'E' 'Bis' 'C' 'D' '3' 'I' 'G'
 '6' 'N' '5' '8' 'Baix' '4' 'Esquerra' '7' 'F' '2C' 'Izquierda' 'L' 'H'
 'K' '9' 'T' 'M' 'S' 'J' '13' 'c' 'C-1' 'B1' '10' 'Ruyra' 'Q' 'dta' '23'
 'Llevant' '21' 'Y' 'Verdaguer' 'a' 'A2' 'Int' '1 B' 'Dreta' 'Baix B'
 'porta 118' 'porta 159' 'P' '6é' 'subterrassa' 'esc' 'AP' 'DR' '25' 'Ap'
 'C1' '15' '16' 'pol 4' 'casa' 'porta 406' '11' 'k' 'esqr' '1 D' 'TRES'
 'pol4' 'h' '17' 'DRETA' 'VERGE REMEI' 'unic' 'Cal Paiant' '1-3A' '0'
 'Pol 4' 'ESQUERRA' 'M-48' 'E1' '12' '14' 'II' 'III' 'IV' 'C-A' '1B'
 'Illa G-2' 'Illa F3' '1 B1' 'F-22' 'DC' 'd' 'B2' 'NR' '4C' 'A1' 'X' 'D-A'
 'B 1' 'Planta 1' '16B' '45' '.' '5-E' '00' 'III-IV' '1C' 'R' 'B3' '66'
 '50' 'B 18' 'Beta' 'A 4' 'A 2' '01' 'C2' '5B' '71' 'D IV' 'El Coto' 'D 4'
 '18' 'Cadaquès' 'Pinamar' 'º' 'Torre II' '7B' '30-12' 'Po' '32' '1D' '3C'
 'Alba 1' 'Saga' 'Entresol' '47' 'Omega' '15b' '39' 'DB' 'Stela' 'Escala'
 '19' 'Garbí' 'e-b' 'A. Bxs-2' 'NI' 'Z' 'BF' '2B' 'Bahia III' 'D2' 'D3'
 '102' 'TRAMUNTANA' 'casa 13' 'D4' 'pol 1' 'Nord' '303' '201' 'DU' '29'
 '3D' 'Pol.11' 'V' 'H1' 'E-1' 'E4' '107' '310' '31' 'C(1)' 'parcela 36'
 'ap33' 'Parc.126' '13-33' '73' 'Aja' 'CADI' 'A-1' '4D' 'no' '1b' '203'
 'NO' '5ENA' 'MONTSENY' '3E' 'CARLINA' '1-A' 'Es:1' '5 C/E' '77' 'L5' 'F2'
 '91' '3 L1' 'Pol 13' 'XALOC' 'bustia 455' 'PAR' 'Central' 'b2' 'ER'
 'Pol. 9' 'B-1' 'Porta 232' 'M1' 'ESQ' '-' 'esc a' '02' '33' 'CASA 12'
 'PAR 113' '75' '1er' 'BAJO' 'H-23' '20' 'A-B' 'parcel·la 99'
 'Camí de Surp' 'única' 'B-2' 'VIII' 'XI' 'XII' 'XVI' 'XVII' 'VII' 'IX'
 'XIII' 'VI' 'XIV' 'XIX' 'D1' 'i' 'B6' 'C-9' '22' '28' 'D-1' 'ATICO' '4B'
 '1F' 'E2' '3B' '37A' 'Escala 1' 'Rústega' 'O' 'B5' 'XVIII' 'F1' 'Pol. 14'
 'LL' 'Dr' '44' 'Esc. 1' 'Escala 3' 'Esc.5' 'Esc. D' 'Esc. 3' 'Esc.1'
 'Esc. B' 'Esc. 2' 'Esc. A' 'Esc. L' 'Esc. E' 'Esc. C' 'E10' 'EST' '5-6'
 '14D' 'Apmt. 27B' 'izq' 'IZ' 'w' '30' 'x' 'B4' '2APT' 'e'
 'CASA FONS Esqrr' 'f' 'AA' 'DERECHA' 'bis' 'Drt' 'primera planta' '24'
 '35' '49' 'c2' '34' 'Baix A' 'Esc C' 'E3' 'V1' 'V3' 'ENTRESOL' '15B' 'CA'
 'ca' 'u' 'p' '1-2' 'g' 'S-2' 'POL4' 'Pol7']

Unique values in column 'Bloc':
[nan 'A' 'B' ... 'Parc. 55' 'Pins' 'Mas Carnicer']

Unique values in column 'Municipi':
['Castelldefels' 'Barcelona' 'Sitges' 'Vilanova i la Geltrú' 'Campins'
 'Olèrdola' 'Sant Boi de Llobregat' 'Torrelles de Llobregat' 'Calella'
 'Malgrat de Mar' 'Santa Coloma de Gramenet' 'Pineda de Mar'
 'Canet de Mar' "Hospitalet de Llobregat, l'" 'Masnou, el'
 'Sant Cugat del Vallès' 'Corbera de Llobregat' 'Puig-reig' 'Badalona'
 'Mataró' "Caldes d'Estrac" 'Teià' 'Begues' 'Llacuna, la' 'Collsuspina'
 'Capellades' 'Lladurs' 'Tavertet' 'Roda de Ter' 'Perafita' 'Muntanyola'
 'Pobla de Claramunt, la' 'Borredà' 'Clariana de Cardener'
 'Monistrol de Montserrat' 'Navès' 'Gironella' 'Castellbell i el Vilar'
 'Manresa' 'Igualada' 'Planoles' 'Vall de Bianya, la' 'Queralbs'
 'Sant Ferriol' 'Tossa de Mar' 'Capmany' 'Sant Feliu de Pallerols' 'Toses'
 'Lloret de Mar' 'Sant Martí de Llémena' 'Calonge i Sant Antoni' 'Ordis'
 'Torroella de Montgrí' 'Santa Pau' 'Setcases' 'Vilademuls' 'Alp'
 'Palamós' 'Palafrugell' 'Roses' "Escala, l'" "Castelló d'Empúries"
 'Blanes' 'Maià de Montcal' 'Cadaqués' 'Pals' 'Ribes de Freser'
 'Sant Feliu de Guíxols' "Castell d'Aro, Platja d'Aro i s'Agaró"
 'Maçanet de Cabrenys' 'Lladó' 'Puigcerdà'
 "Cruïlles, Monells i Sant Sadurní de l'Heura" 'Agullana' 'Camprodon'
 'Mieres' 'Molló' 'Girona' 'Olot' 'Portbou' 'Vilanant'
 'Sant Pere Pescador' 'Rabós' 'Sant Hilari Sacalm' 'Preses, les'
 'Saus, Camallera i Llampaies' 'Verges' 'Ultramort' 'Sant Gregori' 'Breda'
 'Vilamaniscle' 'Riumors' 'Regencós' 'Banyoles' 'Besalú' 'Tarrés'
 'Sarroca de Bellera' 'Vall de Boí, la' 'Espot' 'Plans de Sió, els'
 'Montferrer i Castellbó' 'Valls de Valira, les' 'Biosca' 'Coll de Nargó'
 'Josa i Tuixén' 'Alt Àneu' 'Alins' 'Sant Ramon' 'Vallbona de les Monges'
 'Pont de Bar, el' 'Bellver de Cerdanya' 'Vansa i Fórnols, la' 'Cervera'
 'Talarn' 'Vall de Cardós' 'Fígols i Alinyà' 'Salou'
 'Banyeres del Penedès' 'Blancafort' 'Cunit' 'Vila-seca'
 "Espluga de Francolí, l'" 'Cambrils' 'Calafell' 'Mont-roig del Camp'
 "Vandellòs i l'Hospitalet de l'Infant" 'Pallaresos, els' 'Falset'
 'Montbrió del Camp' 'Montblanc' 'Vimbodí' 'Vendrell, el' 'Tarragona'
 'Margalef' 'Savallà del Comtat' 'Deltebre' 'Arnes' 'Horta de Sant Joan'
 'Mas de Barberans' 'Vilalba dels Arcs' 'Ulldecona' 'Batea' 'Perelló, el'
 'Camarles' 'Ràpita, la' "Ampolla, l'" 'Prat de Comte' 'Rasquera'
 'Vielha e Mijaran' 'Naut Aran' 'Gavà' 'Santa Susanna' 'Vallromanes'
 'Cubelles' 'Sant Cebrià de Vallalta' 'Sant Pol de Mar' 'Arenys de Mar'
 'Santa Eulàlia de Ronçana' 'Montseny' 'Fogars de Montclús'
 'Sant Quirze Safaja' 'Caldes de Montbui' 'Gualba' 'Solsona'
 'Sant Llorenç de Morunys' 'Odèn' 'Gósol' 'Bagà' 'Espinelves'
 'Castellar del Riu' 'Saldes' 'Berga' 'Rupit i Pruit' 'Vidrà'
 'Vilanova de Sau' 'Taradell' "Sant Sadurní d'Osormort" 'Olost'
 'Pobla de Lillet, la' 'Santa Maria de Merlès' 'Talamanca'
 'Sant Mateu de Bages' 'Guardiola de Berguedà' 'Santa Eugènia de Berga'
 'Centelles' 'Avià' 'Viver i Serrateix' 'Sant Salvador de Guardiola'
 'Port de la Selva, el' 'Isòvol' 'Begur' 'Vall-llobrega' 'Colera'
 'Figueres' 'Ripoll' 'Llagostera' 'Llançà' 'Campdevànol' 'Mont-ras'
 'Porqueres' 'Esponellà' 'Garriguella' 'Sant Pau de Segúries'
 'Guils de Cerdanya' 'Vilallonga de Ter' 'Sales de Llierca'
 'Sant Feliu de Buixalleu' 'Osor' 'Fornells de la Selva' 'Montagut i Oix'
 'Sant Llorenç de la Muga' 'Arbúcies' 'Albanyà' 'Fontanals de Cerdanya'
 'Pardines' "Planes d'Hostoles, les" "Santa Cristina d'Aro" 'Riudarenes'
 'Llosses, les' 'Vallfogona de Ripollès' 'Sant Miquel de Campmajor'
 'Sant Joan de les Abadesses' 'Tortosa' 'Soriguera' 'Pont de Suert, el'
 'Senterada' "Guingueta d'Àneu, la" 'Lladorre' 'Pobla de Segur, la'
 'Prullans' 'Sort' 'Torre de Cabdella, la' 'Vilanova de la Barca'
 'Camarasa' 'Àger' "Esterri d'Àneu" 'Llavorsí' 'Lles de Cerdanya'
 'Bassella' 'Organyà' 'Oliana' 'Alòs de Balaguer' 'Torredembarra'
 'Creixell' 'Altafulla' 'Roda de Berà' 'Vinyols i els Arcs' 'Prades'
 'Vilanova de Prades' 'Ulldemolins' 'Cornudella de Montsant' 'Poboleda'
 'Alcanar' "Ametlla de Mar, l'" 'Amposta' "Riba-roja d'Ebre"
 'Pobla de Massaluca, la' 'Tivissa' 'Bot' 'Vilamòs' 'Bossòst' 'Arres'
 'Les' 'Sabadell' 'Garriga, la' 'Cerdanyola del Vallès' 'Granollers'
 'Vilassar de Mar' 'Sant Celoni' 'Papiol, el' 'Martorell' 'Cabrera de Mar'
 'Cervelló' 'Sant Vicenç de Montalt' 'Sant Pere de Riudebitlles'
 'Sant Andreu de Llavaneres' 'Viladecans' "Sant Sadurní d'Anoia" 'Cabrils'
 'Sant Joan Despí' 'Montcada i Reixac' 'Sant Adrià de Besòs'
 'Cornellà de Llobregat' 'Montornès del Vallès' 'Palafolls'
 'Sant Feliu de Llobregat' 'Cardedeu' 'Mollet del Vallès'
 'Vilafranca del Penedès' 'Tordera' 'Canovelles'
 'Santa Maria de Palautordera' 'Prat de Llobregat, el'
 'Santa Margarida i els Monjos' 'Terrassa' 'Subirats'
 'Sant Esteve Sesrovires' 'Vallirana' 'Sant Just Desvern'
 'Esplugues de Llobregat' 'Rubí' 'Barberà del Vallès'
 'Vilanova del Vallès' 'Parets del Vallès' 'Montmeló'
 'Sant Andreu de la Barca' 'Premià de Mar' 'Collbató'
 'Santa Perpètua de Mogoda' 'Palau-solità i Plegamans' 'Abrera'
 'Sant Antoni de Vilamajor' 'Alella' 'Llagosta, la' 'Torrelles de Foix'
 'Sant Pere de Ribes' 'Molins de Rei' 'Bigues i Riells del Fai del Fai'
 'Castellterçol' 'Figaró-Montmany' 'Castellbisbal' 'Ripollet'
 'Premià de Dalt' 'Franqueses del Vallès, les' 'Sant Llorenç Savall'
 'Cànoves i Samalús' 'Sant Martí Sarroca' 'Sant Esteve de Palautordera'
 'Aiguafreda' 'Vilassar de Dalt' 'Gelida' 'Argentona' 'Font-rubí'
 'Avinyonet del Penedès' 'Manlleu' 'Viladrau' 'Montmaneu'
 'Coma i la Pedra, la' 'Tona' 'Olius' "Castellar de N'Hug" 'Riner'
 "Santa Maria d'Oló" "Esquirol, l'" 'Sant Vicenç de Castellet' 'Alpens'
 'Bruc, el' 'Sant Julià de Vilatorta' 'Avinyó' 'Sant Joan de Vilatorrada'
 'Masies de Voltregà, les' 'Nou de Berguedà, la' 'Cardona' 'Vic'
 'Sant Jaume de Frontanyà' 'Navarcles' 'Seva' 'Torelló' "Espunyola, l'"
 'Sagàs' 'Sallent' 'Prats de Rei, els' 'Castellnou de Bages' 'Lluçà'
 'Sant Quirze de Besora' 'Calaf' 'Santpedor' 'Pujalt' 'Prats de Lluçanès'
 'Tavèrnoles' 'Vallcebre' 'Calders' 'Jorba' 'Navàs' 'Súria' 'Cercs'
 'Masquefa' 'Sant Fruitós de Bages' 'Guixers' 'Moià'
 'Monistrol de Calders' 'Montmajor' 'Sant Martí de Centelles' 'Casserres'
 'Fígols' 'Castellar de la Ribera' 'Santa Margarida de Montbui' 'Sora'
 'Sant Pere de Torelló' 'Masies de Roda, les' 'Caldes de Malavella'
 'Santa Coloma de Farners' 'Sils' 'Sant Julià de Ramis' 'Vidreres'
 'Castellfollit de la Roca' 'Maçanet de la Selva' 'Riells i Viabrea'
 "Bisbal d'Empordà, la" "Vall d'en Bas, la" 'Gombrèn' 'Ogassa'
 'Selva de Mar, la' 'Salt' 'Campelles' 'Pontós' 'Jonquera, la'
 'Sant Climent Sescebes' 'Anglès' 'Cassà de la Selva' 'Amer' 'Vilafant'
 'Sarrià de Ter' 'Vilajuïga' 'Pont de Molins' 'Bordils'
 'Cornellà del Terri' 'Viladamat' 'Susqueda' 'Riudellots de la Selva'
 'Darnius' 'Celrà' 'Meranges' 'Llívia' 'Avinyonet de Puigventós' 'Torrent'
 'Cantallops' 'Bolvir' 'Llanars' 'Albons' "Vilobí d'Onyar" 'Forallac'
 'Ger' 'Navata' 'Tortellà' 'Peralada' 'Sant Joan les Fonts' 'Camós'
 'Palau-sator' 'Bàscara' 'Cellera de Ter, la' 'Vilabertran'
 'Sant Aniol de Finestres' 'Terrades' 'Gualta' 'Pera, la' 'Madremanya'
 'Cabanelles' 'Palau-saverdera' 'Pau' 'Serinyà' 'Llers' 'Ventalló' 'Corçà'
 'Ullastret' 'Vajol, la' 'Sant Martí Vell' 'Mollet de Peralada' 'Espolla'
 'Torroella de Fluvià' 'Lleida' 'Montellà i Martinet' "Seu d'Urgell, la"
 'Tremp' 'Vilagrassa' 'Mollerussa' 'Castell de Mur' 'Peramola' 'Vilaller'
 'Balaguer' 'Alfarràs' 'Cubells' 'Salàs de Pallars' 'Prats i Sansor'
 'Rialp' 'Ponts' 'Torà' 'Algerri' 'Avellanes i Santa Linya, les'
 'Artesa de Segre' 'Tírvia' 'Vilanova de Meià' 'Agramunt' 'Estamariu'
 'Alcarràs' "Ribera d'Urgellet" 'Granadella, la' 'Tàrrega' 'Bellpuig'
 'Torres de Segre' 'Borges Blanques, les' 'Fondarella' 'Torrefarrera'
 'Os de Balaguer' 'Miralcamp' 'Alguaire' "Palau d'Anglesola, el"
 'Arsèguel' 'Granyena de les Garrigues' 'Castelldans' 'Granyanella'
 'Farrera' "Ivars d'Urgell" 'Linyola' 'Alàs i Cerc' 'Vilosell, el'
 'Baronia de Rialb, la' 'Massoteres' 'Llimiana' 'Arbeca' 'Riu de Cerdanya'
 'Guissona' 'Conca de Dalt' 'Cava' 'Preixens' 'Soses'
 'Vallfogona de Riucorb' 'Morell, el' 'Reus' 'Aiguamúrcia' 'Riudoms'
 'Valls' 'Solivella' 'Gratallops' 'Vilella Baixa, la'
 'Bellmunt del Priorat' 'Morera de Montsant, la' 'Alcover'
 'Sant Jaume dels Domenys' "Arboç, l'" 'Passanant i Belltall i Belltall'
 'Pobla de Mafumet, la' "Vilanova d'Escornalbou" 'Arbolí'
 'Selva del Camp, la' 'Riera de Gaià, la' 'Porrera' 'Vilaverd' 'Pontils'
 'Botarell' 'Pratdip' 'Capafonts' 'Colldejou' 'Salomó' 'Canonja, la'
 'Albinyana' 'Guiamets, els' 'Perafort' 'Mont-ral' 'Rodonyà'
 'Torroja del Priorat' 'Gandesa' 'Flix' 'Vinebre' 'Fatarella, la'
 'Móra la Nova' "Aldea, l'" 'Santa Bàrbara' 'Sénia, la' 'Benifallet'
 'Pinell de Brai, el' 'Xerta' 'Benissanet' "Móra d'Ebre" 'Masdenverge'
 'Alfara de Carles' 'Pontons' 'Sant Pere de Vilamajor' 'Tagamanent'
 'Arenys de Munt' "Lliçà d'Amunt" 'Castellar del Vallès'
 'Castellet i la Gornal' 'Canyelles' 'Sentmenat' "Ametlla del Vallès, l'"
 'Òrrius' 'Viladecavalls' 'Matadepera' 'Dosrius' 'Montgat'
 'Sant Quirze del Vallès' 'Vallgorguina' 'Sant Iscle de Vallalta'
 'Olivella' 'Rellinars' 'Roca del Vallès, la' 'Fogars de la Selva'
 'Vacarisses' 'Castellcir' 'Sant Fost de Campsentelles'
 'Sant Quintí de Mediona' 'Llinars del Vallès' 'Esparreguera' 'Pallejà'
 'Tiana' 'Mediona' 'Puigdàlber' "Sant Llorenç d'Hortons" 'Cabanyes, les'
 'Pla del Penedès, el' 'Bigues i Riells del Fai' 'Sant Cugat Sesgarrigues'
 'Castellví de Rosanes' 'Sant Vicenç dels Horts' 'Sant Feliu de Codines'
 'Lliçà de Vall' 'Santa Coloma de Cervelló' 'Castellví de la Marca'
 'Vilobí del Penedès' 'Olesa de Bonesvalls' 'Balenyà' 'Torrelavit'
 'Pont de Vilomara i Rocafort, el' 'Granada, la' 'Polinyà' 'Martorelles'
 'Pacs del Penedès' 'Gallifa' 'Mura' 'Montclar' "Estany, l'"
 'Sant Bartomeu del Grau' 'Santa Maria de Miralles' 'Olvan' 'Piera'
 'Torre de Claramunt, la' 'Gisclareny' 'Sobremunt' 'Oristà' 'Rubió'
 'Vilada' 'Sant Martí de Tous' 'Sant Boi de Lluçanès' 'Artés' 'Bellprat'
 'Balsareny' 'Copons' 'Granera' 'Sant Feliu Sasserra' 'Gurb'
 "Vallbona d'Anoia" 'Marganell' 'Quar, la' 'Brull, el'
 'Sant Martí Sesgueioles' 'Capolat' "Cabrera d'Anoia" 'Veciana'
 "Castell de l'Areny" 'Calldetenes' 'Òdena' 'Sant Hipòlit de Voltregà'
 'Santa Cecília de Voltregà' 'Santa Maria de Besora' 'Fonollosa'
 'Sant Pere Sallavinera' "Sant Martí d'Albars" 'Pinós'
 'Hostalets de Pierola, els' 'Sant Agustí de Lluçanès' 'Argençola'
 'Pinell de Solsonès' 'Montesquiu' 'Sant Julià de Cerdanyola' 'Callús'
 'Carme' 'Castellfollit del Boix' 'Castellolí' 'Aguilar de Segarra' 'Gaià'
 'Malla' 'Sant Jaume de Llierca' 'Cistella'
 'Sant Julià del Llor i Bonmatí' 'Riudaura' 'Foixà' 'Vilaür' 'Parlavà'
 'Sant Mori' 'Campllong' 'Fontcoberta' 'Argelaguer' 'Bescanó'
 "Bellcaire d'Empordà" 'Beuda' 'Urús' 'Das' "Canet d'Adri"
 "Tallada d'Empordà, la" 'Rupià' 'Sant Jordi Desvalls' 'Garrigoles'
 'Brunyola i Sant Martí Sapresa' 'Quart' 'Hostalric' 'Ullà' 'Borrassà'
 'Fontanilles' 'Garrigàs' 'Aiguaviva' 'Serra de Daró' 'Vilablareix'
 "Armentera, l'" 'Vilopriu' 'Jafre' 'Llambilles' 'Cabanes'
 'Sant Miquel de Fluvià' 'Biure' 'Crespià' 'Juià' 'Siurana' 'Vilamacolum'
 'Viladasens' 'Sant Andreu Salou' 'Cervià de Ter' 'Pedret i Marzà'
 'Masarac i Vilarnadal' 'Colomers' 'Boadella i les Escaules' 'Fortià'
 'Vilamalla' 'Palau de Santa Eulàlia' 'Massanes' 'Palol de Revardit'
 'Sant Joan de Mollet' 'Vila-sacra' 'Flaçà' 'Saus' 'Vilanova de Bellpuig'

In [7]:
# Filtrar por tipo de modalidad
df = df[~df['Tipus establiment'].isin(['Càmping', 'Hotels'])]

# Borrar columnas no relevantes
# Lista de columnas a eliminar
columns_to_drop = [
    'Tipus de via', 'Nom de la via', 'Número', 'Pis', 'Porta',
    'Escala', 'Bloc', 'Dígit de control', 'Estat'
]

# Eliminar las columnas
df = df.drop(columns=columns_to_drop)
df

,Tipus establiment,Número inscripció,Rètol,Codi Postal,Municipi,Codi Municipi (IDESCAT),Comarca,Codi Comarca (IDESCAT),Província,Referència cadastral,...,Unitat d'allotjament,Total places,Total estances,SSTT,Marca turística,CIF,Raó Social del titular,Nom del titular,Primer cognom,Segon cognom
0,Apartaments Turístics,ATB-000002,Voramar,8860,Castelldefels,80569,Baix Llobregat,11,Barcelona,NaN,...,Apartaments,36.0,18.0,Barcelona,Costa Barcelona,B63470942,"CASTELLISCON, SL",No aplica,No aplica,No aplica
1,Apartaments Turístics,ATB-000003,Gutenberg,8001,Barcelona,80193,Barcelonès,13,Barcelona,NaN,...,Apartaments,170.0,85.0,Barcelona,Barcelona,A08433989,"APARTAMENTOS GUTENBERG, SA",No aplica,No aplica,No aplica
2,Apartaments Turístics,ATB-000004,Montserrat,8870,Sitges,82704,Garraf,17,Barcelona,NaN,...,Apartaments,12.0,6.0,Barcelona,Costa Barcelona,No aplica,No aplica,Montserrat,Bartes,Abella
3,Apartaments Turístics,ATB-000005,Silver,8012,Barcelona,80193,Barcelonès,13,Barcelona,NaN,...,Apartaments,98.0,49.0,Barcelona,Barcelona,A08139859,"PROYECTOS E INMUEBLES, S. A",No aplica,No aplica,No aplica
4,Apartaments Turístics,ATB-000006,Castellmar,8860,Castelldefels,80569,Baix Llobregat,11,Barcelona,NaN,...,Apartaments,22.0,10.0,Barcelona,Costa Barcelona,B61933511,"MARFINA APARTAMENTOS, SL",No aplica,No aplica,No aplica
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112555,Turisme rural,PVA-000639,Bòrda Gilhamuc,25540,Les,251214,Aran,39,Lleida,NaN,...,Habitació,6.0,3.0,Val d'Aran,Val d'Aran,No aplica,No aplica,Mireia,Boya,Busquet
112556,Turisme rural,PVA-000640,Pico Rusell,25551,"Bòrdes, Es",250576,Aran,39,Lleida,NaN,...,Habitació,10.0,4.0,Val d'Aran,Val d'Aran,No aplica,No aplica,Juan Luís,De,Pablo Pérez
112557,Turisme rural,PVA-000641,CASA CHIN,25539,Vielha e Mijaran,252430,Aran,39,Lleida,NaN,...,Habitació,12.0,5.0,Val d'Aran,Val d'Aran,No aplica,No aplica,JORDI,ARJÓ,FRANCÉS
112558,Turisme rural,PVA-001015,TORISME RURAU CASA REY,25537,Vielha e Mijaran,252430,Aran,39,Lleida,NaN,...,Habitació,12.0,5.0,Val d'Aran,Val d'Aran,No aplica,No aplica,Carmen,Castellarnau,Lafont
112559,Turisme rural,PVA-001379,ES DE PAU AGROTURISME,25598,Naut Aran,250254,Aran,39,Lleida,NaN,...,Habitació,5.0,3.0,Val d'Aran,Val d'Aran,No aplica,No aplica,Jose Maria,Moga,Cortinat

In [8]:
# Eliminar duplicados
df = df.drop_duplicates()
df

,Tipus establiment,Número inscripció,Rètol,Codi Postal,Municipi,Codi Municipi (IDESCAT),Comarca,Codi Comarca (IDESCAT),Província,Referència cadastral,...,Unitat d'allotjament,Total places,Total estances,SSTT,Marca turística,CIF,Raó Social del titular,Nom del titular,Primer cognom,Segon cognom
0,Apartaments Turístics,ATB-000002,Voramar,8860,Castelldefels,80569,Baix Llobregat,11,Barcelona,NaN,...,Apartaments,36.0,18.0,Barcelona,Costa Barcelona,B63470942,"CASTELLISCON, SL",No aplica,No aplica,No aplica
1,Apartaments Turístics,ATB-000003,Gutenberg,8001,Barcelona,80193,Barcelonès,13,Barcelona,NaN,...,Apartaments,170.0,85.0,Barcelona,Barcelona,A08433989,"APARTAMENTOS GUTENBERG, SA",No aplica,No aplica,No aplica
2,Apartaments Turístics,ATB-000004,Montserrat,8870,Sitges,82704,Garraf,17,Barcelona,NaN,...,Apartaments,12.0,6.0,Barcelona,Costa Barcelona,No aplica,No aplica,Montserrat,Bartes,Abella
3,Apartaments Turístics,ATB-000005,Silver,8012,Barcelona,80193,Barcelonès,13,Barcelona,NaN,...,Apartaments,98.0,49.0,Barcelona,Barcelona,A08139859,"PROYECTOS E INMUEBLES, S. A",No aplica,No aplica,No aplica
4,Apartaments Turístics,ATB-000006,Castellmar,8860,Castelldefels,80569,Baix Llobregat,11,Barcelona,NaN,...,Apartaments,22.0,10.0,Barcelona,Costa Barcelona,B61933511,"MARFINA APARTAMENTOS, SL",No aplica,No aplica,No aplica
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112555,Turisme rural,PVA-000639,Bòrda Gilhamuc,25540,Les,251214,Aran,39,Lleida,NaN,...,Habitació,6.0,3.0,Val d'Aran,Val d'Aran,No aplica,No aplica,Mireia,Boya,Busquet
112556,Turisme rural,PVA-000640,Pico Rusell,25551,"Bòrdes, Es",250576,Aran,39,Lleida,NaN,...,Habitació,10.0,4.0,Val d'Aran,Val d'Aran,No aplica,No aplica,Juan Luís,De,Pablo Pérez
112557,Turisme rural,PVA-000641,CASA CHIN,25539,Vielha e Mijaran,252430,Aran,39,Lleida,NaN,...,Habitació,12.0,5.0,Val d'Aran,Val d'Aran,No aplica,No aplica,JORDI,ARJÓ,FRANCÉS
112558,Turisme rural,PVA-001015,TORISME RURAU CASA REY,25537,Vielha e Mijaran,252430,Aran,39,Lleida,NaN,...,Habitació,12.0,5.0,Val d'Aran,Val d'Aran,No aplica,No aplica,Carmen,Castellarnau,Lafont
112559,Turisme rural,PVA-001379,ES DE PAU AGROTURISME,25598,Naut Aran,250254,Aran,39,Lleida,NaN,...,Habitació,5.0,3.0,Val d'Aran,Val d'Aran,No aplica,No aplica,Jose Maria,Moga,Cortinat

In [9]:
# missing values
print("Conteo de valores nulos por columna:")
print(df.isnull().sum())

Conteo de valores nulos por columna:
Tipus establiment               0
Número inscripció               0
Rètol                           1
Codi Postal                     0
Municipi                        0
Codi Municipi (IDESCAT)         0
Comarca                         0
Codi Comarca (IDESCAT)          0
Província                       0
Referència cadastral        98747
Cèdula d'habitabilitat      91928
Grup                       106672
Modalitat                  106672
Categoria                     251
Unitat d'allotjament            4
Total places                81572
Total estances             102475
SSTT                            0
Marca turística                 0
CIF                             1
Raó Social del titular          7
Nom del titular                 0
Primer cognom                   0
Segon cognom                    0
dtype: int64

In [10]:
# código provincia
provincia_counts = df['Província'].value_counts()

# Guardar dataframe como csv
provincia_counts.to_csv('provincia_counts.csv', index=True)

provincia_counts

Província
Girona       47027
Tarragona    32029
Barcelona    24893
Lleida        5434
Name: count, dtype: int64

In [21]:
# Guardar dataframe como csv
df.to_csv('dataset_establiments_clean.csv', index=False)

In [18]:
# Filtrar filas donde 'Província' == 'Girona'
df_girona = df[df['Província'] == 'Girona']

# Contar número de alojamientos por municipio
municipi_counts = df_girona['Municipi'].value_counts().head(10).reset_index()

# Renombrar columnas
municipi_counts.columns = ['Municipi', 'Recompte']

# Guardar como CSV
municipi_counts.to_csv('municipi_counts_top10.csv', index=False)

# Mostrar el resultado
municipi_counts

                                Municipi  Recompte
0                                  Roses      5371
1                    Castelló d'Empúries      3676
2                          Lloret de Mar      3296
3                             Escala, l'      3276
4  Castell d'Aro, Platja d'Aro i s'Agaró      2950
5                            Palafrugell      2789
6                   Torroella de Montgrí      2681
7                  Calonge i Sant Antoni      2442
8                                  Begur      1773
9                                 Llançà      1692

In [ ]:
# Filtrar filas donde 'Província' == 'Girona'
df_tenidors = df[df['Província'] == 'Girona']

# Contar número de alojamientos por municipio
municipi_counts = df_girona['Municipi'].value_counts().head(10).reset_index()

# Renombrar columnas
municipi_counts.columns = ['Municipi', 'Recompte']

# Guardar como CSV
municipi_counts.to_csv('municipi_counts_top10.csv', index=False)

# Mostrar el resultado
municipi_counts

In [24]:
# Agrupar por 'Província' y 'Nombre_completo' y contar
df['Nombre_completo'] = df['Nom del titular']+ '-' + df['Primer cognom'] + '-' + df['Segon cognom']
df = df[df['Nombre_completo'] != 'No aplica-No aplica-No aplica']

grouped = df.groupby(['Província', 'Nombre_completo']).size().reset_index(name='Counts')

# Calcular el total por provincia
totals = grouped.groupby('Província')['Counts'].transform('sum')

# Calcular el porcentaje por propietario respecto al total de su provincia
grouped['Porcentaje'] = (grouped['Counts'] / totals * 100).round(2)

# Reordenar columnas
result = grouped[['Nombre_completo', 'Counts', 'Província', 'Porcentaje']]

# Guardar como CSV
result.to_csv('propietarios_por_provincia.csv', index=False)

# Mostrar resultado
result

                       Nombre_completo  Counts  Província  Porcentaje
0            .-CASA FARRERAS-No aplica       1  Barcelona        0.17
1                  AGUSTIN-MORERA-GUMA       3  Barcelona        0.52
2             ALBERT-CAMPINS-CASANOVAS       1  Barcelona        0.17
3     ALVARO-ALVAREZ DE LA CAMPA-FAYOS       2  Barcelona        0.34
4              AMADEO-SABATA-VILAREDES       1  Barcelona        0.17
...                                ...     ...        ...         ...
1711        Tomas Vicente-Catalan-Sanz       1  Tarragona        0.27
1712              Vicenta-Roselló-Roca       1  Tarragona        0.27
1713                 YOLANDA-VIVES-MAS       1  Tarragona        0.27
1714               Àngel-Llasera-Ramos       1  Tarragona        0.27
1715                 Òscar-Godes-Altés       1  Tarragona        0.27

[1716 rows x 4 columns]

In [27]:
# Agrupar por 'Província' y 'Nombre_completo' y contar
grouped = df.groupby(['Província', 'Nombre_completo']).size().reset_index(name='Counts')

# Calcular el total por provincia para el porcentaje
grouped['Total_provincia'] = grouped.groupby('Província')['Counts'].transform('sum')
grouped['Porcentaje'] = (grouped['Counts'] / grouped['Total_provincia'] * 100).round(2)

# Eliminar columna auxiliar
grouped = grouped.drop(columns='Total_provincia')

# Reordenar columnas
result = grouped[['Nombre_completo', 'Counts', 'Província', 'Porcentaje']]

# Obtener lista única de provincias
provincias = result['Província'].unique()

# Guardar un CSV para cada provincia con solo el top 10
for prov in provincias:
    df_prov = result[result['Província'] == prov].sort_values(by='Counts', ascending=False).head(10)

    # Mostrar en consola
    print(f"🏙️ Top 10 propietarios en {prov}")
    print(df_prov, "\n")

    # Guardar CSV
    filename = f'propietarios_top10_{prov}.csv'.replace(" ", "_")
    df_prov.to_csv(filename, index=False)

🏙️ Top 10 propietarios en Barcelona
                 Nombre_completo  Counts  Província  Porcentaje
375  RAMON MARIA-PELLICER-LLIMOS       5  Barcelona        0.86
9             Adam-Alenyà-Vilaró       5  Barcelona        0.86
198            Jordi-Soler-Nieto       5  Barcelona        0.86
91   Estanislau-Anglerill-Villar       5  Barcelona        0.86
131             JAUME-PRAT-CARDÓ       5  Barcelona        0.86
147     JOSEP-BUSCALLÀ-COROMINAS       4  Barcelona        0.69
92        Ester-Argerich-Ramells       4  Barcelona        0.69
392            Remei-Puig-Deumal       4  Barcelona        0.69
350          Natividad-Uson-Pons       3  Barcelona        0.52
353              Neus-Saz-Carazo       3  Barcelona        0.52

🏙️ Top 10 propietarios en Girona
                  Nombre_completo  Counts Província  Porcentaje
477           Antoni-Arqués-Martí       6    Girona        0.87
622              JOAN-COLL-FERRER       6    Girona        0.87
602          Helena-Picola-Masdeu       6    Girona        0.87
812            Martí-Torras-Palou       5    Girona        0.72
504                Carme-Bo-Tubau       5    Girona        0.72
569        FRANCESC-SOLA-BUSQUETS       5    Girona        0.72
754  MARIA ARACELI-RODRIGUEZ-VILA       5    Girona        0.72
818           Miquel-Camps-Badosa       5    Girona        0.72
452          Albert-Auquer-Pujals       5    Girona        0.72
838               Núria-Meya-Alis       4    Girona        0.58

🏙️ Top 10 propietarios en Lleida
                Nombre_completo  Counts Província  Porcentaje
1260  Maria Isabel-Guardia-Solé       8    Lleida        1.29
1087   Jaume-Montaner-Capdevila       7    Lleida        1.13
1375    Trinitat-Agulló-Buñesch       6    Lleida        0.97
945     ANNA Mº-CARDONA-ANGRILL       5    Lleida        0.81
1244   Marc-Garrigasait-Colomés       5    Lleida        0.81
1157          Josep-Call-Prunés       5    Lleida        0.81
979    Antònia-Gabriel-Caselles       4    Lleida        0.65
1003         Concepció-Vila-Riu       4    Lleida        0.65
959   Alberto-Cierco-Fondevilla       4    Lleida        0.65
1232  MARIE JOSE-GUIX-No aplica       4    Lleida        0.65

🏙️ Top 10 propietarios en Tarragona
                    Nombre_completo  Counts  Província  Porcentaje
1392     Agnès Maria-Brenner-Stanzl       4  Tarragona        1.07
1589              MARC-MAJEM-BOFILL       4  Tarragona        1.07
1494           Ina-Rahbek-No aplica       4  Tarragona        1.07
1498            Isabel-Vila-Bigorda       4  Tarragona        1.07
1642   Montserrat-Falgueras-Alabart       3  Tarragona        0.80
1595        MARIA PILAR-GILI-CRUSET       3  Tarragona        0.80
1590     MARIA ANGELS-ROMERO-BAILON       3  Tarragona        0.80
1676          ROSER-FERRE-RODRIGUEZ       3  Tarragona        0.80
1522  Joaquim Miquel-Manzano-Martín       3  Tarragona        0.80
1569           Lluís-Corbella-Jordi       3  Tarragona        0.80

In [28]:
# Agrupar por 'Província' y 'Nombre_completo' y contar
grouped = df.groupby(['Província', 'Nombre_completo']).size().reset_index(name='Counts')

# Calcular el total por provincia para el porcentaje
grouped['Total_provincia'] = grouped.groupby('Província')['Counts'].transform('sum')
grouped['Porcentaje'] = (grouped['Counts'] / grouped['Total_provincia'] * 100).round(2)

# Eliminar columna auxiliar
grouped = grouped.drop(columns='Total_provincia')

# Reordenar columnas
result = grouped[['Nombre_completo', 'Counts', 'Província', 'Porcentaje']]

# Obtener lista única de provincias
provincias = result['Província'].unique()

# Lista para guardar DataFrames de cada top10 provincial
top10_list = []

for prov in provincias:
    df_prov = result[result['Província'] == prov].sort_values(by='Counts', ascending=False).head(10)
    top10_list.append(df_prov)

# Concatenar todos los top10 en un solo DataFrame
df_top10_all = pd.concat(top10_list)

# Guardar todo en un solo CSV
df_top10_all.to_csv('propietarios_top10_todas_provincias.csv', index=False)

df_top10_all

                    Nombre_completo  Counts  Província  Porcentaje
375     RAMON MARIA-PELLICER-LLIMOS       5  Barcelona        0.86
9                Adam-Alenyà-Vilaró       5  Barcelona        0.86
198               Jordi-Soler-Nieto       5  Barcelona        0.86
91      Estanislau-Anglerill-Villar       5  Barcelona        0.86
131                JAUME-PRAT-CARDÓ       5  Barcelona        0.86
147        JOSEP-BUSCALLÀ-COROMINAS       4  Barcelona        0.69
92           Ester-Argerich-Ramells       4  Barcelona        0.69
392               Remei-Puig-Deumal       4  Barcelona        0.69
350             Natividad-Uson-Pons       3  Barcelona        0.52
353                 Neus-Saz-Carazo       3  Barcelona        0.52
477             Antoni-Arqués-Martí       6     Girona        0.87
622                JOAN-COLL-FERRER       6     Girona        0.87
602            Helena-Picola-Masdeu       6     Girona        0.87
812              Martí-Torras-Palou       5     Girona        0.72
504                  Carme-Bo-Tubau       5     Girona        0.72
569          FRANCESC-SOLA-BUSQUETS       5     Girona        0.72
754    MARIA ARACELI-RODRIGUEZ-VILA       5     Girona        0.72
818             Miquel-Camps-Badosa       5     Girona        0.72
452            Albert-Auquer-Pujals       5     Girona        0.72
838                 Núria-Meya-Alis       4     Girona        0.58
1260      Maria Isabel-Guardia-Solé       8     Lleida        1.29
1087       Jaume-Montaner-Capdevila       7     Lleida        1.13
1375        Trinitat-Agulló-Buñesch       6     Lleida        0.97
945         ANNA Mº-CARDONA-ANGRILL       5     Lleida        0.81
1244       Marc-Garrigasait-Colomés       5     Lleida        0.81
1157              Josep-Call-Prunés       5     Lleida        0.81
979        Antònia-Gabriel-Caselles       4     Lleida        0.65
1003             Concepció-Vila-Riu       4     Lleida        0.65
959       Alberto-Cierco-Fondevilla       4     Lleida        0.65
1232      MARIE JOSE-GUIX-No aplica       4     Lleida        0.65
1392     Agnès Maria-Brenner-Stanzl       4  Tarragona        1.07
1589              MARC-MAJEM-BOFILL       4  Tarragona        1.07
1494           Ina-Rahbek-No aplica       4  Tarragona        1.07
1498            Isabel-Vila-Bigorda       4  Tarragona        1.07
1642   Montserrat-Falgueras-Alabart       3  Tarragona        0.80
1595        MARIA PILAR-GILI-CRUSET       3  Tarragona        0.80
1590     MARIA ANGELS-ROMERO-BAILON       3  Tarragona        0.80
1676          ROSER-FERRE-RODRIGUEZ       3  Tarragona        0.80
1522  Joaquim Miquel-Manzano-Martín       3  Tarragona        0.80
1569           Lluís-Corbella-Jordi       3  Tarragona        0.80